[project]
name = "keyboard-analysis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "dotenv>=0.9.9",
    "matplotlib>=3.10.1",
    "pandas>=2.2.3",
    "pynput>=1.8.1",
    "seaborn>=0.13.2",
]
